### ISSUE TITLE
Nach dem Neustart klappt's irgendwie nicht mehr

### ISSUE THREAD

**Issue by djsunrise19** [paviro/MagicMirror-Modules#3]
Hi,

danke erstmal für dein Script, eine sehr coole Idee! Ich habe deine Schritte alle soweit befolgt. Nach den Installationen (habe ein PI 2 Model B und Jessie) habe ich mit `node server.js` das Script gestartet. Eine Rückmeldung bekomme ich da in der Konsole (putty) nicht. Allerdings bei einem Anruf teste ich erfolgreich. Nun starte ich neu (vorher ein script mit `vi call.sh` und dem Inhalt `node /usr/local/bin/SocketIOServer/server.js` erstellt, das als cronjob eingebunden mit `@reboot`. Leider reagiert das Modul nicht mehr und zeigt nix an. Auch ohne Autostart des Scriptes und nochmaligem manuellen Ausführen klappt's nicht mehr.

Ich bin nicht sooo fit mit Linux / Unix. Beachte ich irgendwas nicht?

Viele Grüße
Maurice

**Comment by paviro** [comment]
Hey :)
Ich antworte dir heute Mittag :)
Zu meinem Setup ich starte das zeug mit systemd oder vorher init.d statt als cronjob vielleicht liegt es daran aber ich schaue es mir nachher genauer an.

**Comment by djsunrise19** [comment]
Hi, danke für deine Rückmeldung. Das Verwirrende ist ja, dass auch nach manuellem Eingeben von `node server.js` der Callmonitor nicht (immer) funktioniert. Ich warte ca 1-2min, rufe an, keine Anzeige. Nach Installation der Pakete hat es beim ersten mal aber direkt geklappt. Ich gucke gleich mal wie das mit systemd und initd funktioniert und lege das mal an.

**Comment by Robiv8** [comment]
Hallo, habe das selbe Problem und nach einem erneuten versuch des manuelen starts auch diese Meldung: 
pi@robispi:/usr/local/bin/SocketIOServer $ node server.js
[Mon Mar 28 2016 12:39:59 GMT+0200 (CEST)]: Error: listen EADDRINUSE /tmp/python_node_bridge

Gibts da schon was neues?
Tip?

**Comment by djsunrise19** [comment]
Hi, nach der ganzen Installation habe ich den Mirror einfach mal laufen lassen. Das Skript war gestartet, die Anzeige funktionierte aber noch nicht. Nach ein paar Stunden ging es auf einmal, auch nach dem Neustart. Ich habe keine Ahnung, warum, funktioniert aber seitdem tadellos. Gestern hatte ich beim Sonos Plugin das gleiche Phänomen. Vielleicht brauch er einfach ein Weilchen ;).

**Comment by paviro** [comment]
Heyho,
Sorry ich habe diese Repo irgendwie aus den Augen verloren, da ich an neuen Versionen arbeite. Der Error ` [Mon Mar 28 2016 12:39:59 GMT+0200 (CEST)]: Error: listen EADDRINUSE ` kommt, weil ich die Datei des Unix Sockets nicht lösche, falls sie bereits existiert, um ihn zu beheben einfach  `/tmp/python_node_bridge` manuell löschen.
Am besten wartet ihr aber auf [v2](https://github.com/MichMich/MagicMirror/tree/v2-beta) vom Spiegel, da dort einiges sehr viel einfacher wird, kein manuelles starten der scripts mehr und so weiter.
